name: OPA Test
description: Run Open Policy Agent tests
inputs:
  tests:
    description: Rego file or directory path where to discover tests. Defaults to repository root.
    required: false
    default: ./
runs:
  using: docker
  image: docker://openpolicyagent/opa:latest
  args:
    - test
    - ${{ inputs.tests }}
    - -v
